# -*- coding: utf-8 -*-
"""wims2026_final_V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZUQmLo7hsthFa2ObUXc189CM9coG58Fj

# Libraries
"""

import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, random_split
from transformers import DistilBertModel, DistilBertTokenizerFast
import torch
from torch.optim import AdamW
import json
import random
from sklearn.model_selection import train_test_split
from tqdm import tqdm

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

import torch.nn.functional as F

"""# Functions

## Text Processing
"""

def clear_name(s):
  final_name = ""
  for char in s[::-1]:
      if char == "/" or char == "#":
          break
      final_name = char + final_name
  return final_name

"""## IO"""

def save_json(output_dir, filename, data):
  """
  Save a list or dictionary to a json file.
  :param output_dir:
  :param filename:
  :param data:
  :return:
  """
  if isinstance(data, dict):
      with open(output_dir + "\\" + f"{filename}.json", 'w') as json_file:
          json.dump({str(key): str(val) for key, val in data.items()}, json_file, indent=4)

  elif isinstance(data, list):
      with open(output_dir + "\\" + f"{filename}.json", 'w') as json_file:
          json.dump({str(key): str(val) for key, val in enumerate(data)}, json_file, indent=4)


def save_df(output_dir, filename, df):
  """
  Save a pandas DataFrame to a csv file.
  :param output_dir:
  :param filename:
  :param df:
  :return:
  """
  df.to_csv(output_dir + "\\" + filename + ".csv")

"""## Ontology managers"""

def load_dataset(filename, file_type):
  if file_type == "csv":
    df = pd.read_csv(filename, index_col=0)
  elif file_type == "tsv":
    df = pd.read_csv(filename, sep='\t')

  return df

"""## Filtering after matching"""

def filter_tagged_alignments(df_src_ent, df_tgt_ent, df_matches, score_col):
  src_map = dict(zip(df_src_ent['EntityName'], df_src_ent['use_in_alignment']))
  tgt_map = dict(zip(df_tgt_ent['EntityName'], df_tgt_ent['use_in_alignment']))

  final_matches_data = []
  for _, row in tqdm(df_matches.iterrows(), total=len(df_matches), desc='Filtering Final Matches'):
    if src_map[row['SrcEntity']] and tgt_map[row['TgtEntity']]:
      final_matches_data.append({
          'SrcEntity': row['SrcEntity'],
          'TgtEntity': row['TgtEntity'],
          'Score': row[score_col]
      })
  return pd.DataFrame(final_matches_data)

"""## Preparing Ontology Entities Data"""

class OntologyEntitiesData:
  def __init__(self, df_entities_file, label_col, new_ent_col_name, new_label_col_name) -> None:
     self.label_col = label_col
     self.new_ent_col_name = new_ent_col_name
     self.new_label_col_name = new_label_col_name

     self.df_onto_entities = load_dataset(df_entities_file, 'csv')
     self.df_ent = self.read_onto_entities(label_col)

     self.df_ent = self.rename_columns(new_ent_col_name, new_label_col_name)

     self.max_len = self.max_label_length()

  def max_label_length(self):
    return max([len(x) for x in self.df_ent[self.new_label_col_name]])

  def read_onto_entities(self, label_col):
    self.df_onto_entities = self.df_onto_entities[self.df_onto_entities['EntityType'] == "class"]
    self.df_onto_entities['EntityName'] = self.df_onto_entities['EntityName'].apply(lambda x: str(x))
    self.df_onto_entities['EntityLabel (Extended)'] = self.df_onto_entities['EntityLabel (Extended)'].fillna(
        self.df_onto_entities['EntityLabel (Short)']
    )

    self.df_ent = self.df_onto_entities[['EntityName', label_col]]
    self.df_ent = self.df_ent[self.df_ent['EntityName'] != "Thing"]

    self.df_ent = self.df_ent.reset_index(drop=True)

    return self.df_ent

  def get_dfs(self):
    return self.df_ent, self.df_onto_entities, self.max_len

  def rename_columns(self, new_ent_col_name, new_label_col_name):
    return self.df_ent.rename(columns={"EntityName": new_ent_col_name, self.label_col: new_label_col_name})

"""# Training

## BERT (Cross-Encoder)
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import json
import random
import numpy as np
import pandas as pd

from dataclasses import dataclass
from typing import Dict

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    precision_recall_curve
)

from tqdm.auto import tqdm

from sentence_transformers.cross_encoder import CrossEncoder


# ============================================================
# CONFIG
# ============================================================

@dataclass
class CrossEncoderTrainingConfig:

    model_name: str
    dataset_path: str
    output_dir: str

    batch_size: int = 64
    epochs: int = 5
    learning_rate: float = 2e-5
    max_length: int = 512

    validation_split: float = 0.2
    random_seed: int = 42

    early_stopping_patience: int = 2

    gradient_accumulation_steps: int = 1

    weight_decay: float = 0.01

    num_workers: int = 4

    # focal loss
    focal_gamma: float = 2.0

    # optimized automatically from class distribution
    focal_alpha: float = None

    threshold: float = 0.5

    fp16: bool = True

    pin_memory: bool = True


class WeightedFocalLoss(nn.Module):
    def __init__(
        self,
        alpha=None,
        gamma=2.0,
        reduction="mean"
    ):
        super().__init__()

        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction

    def forward(
        self,
        logits,
        targets
    ):

        targets = targets.long()

        ce_loss = F.cross_entropy(
            logits,
            targets,
            reduction="none",
            weight=self.alpha
        )

        pt = torch.exp(-ce_loss)

        focal_loss = (
            (1 - pt) ** self.gamma
        ) * ce_loss

        if self.reduction == "mean":
            return focal_loss.mean()

        elif self.reduction == "sum":
            return focal_loss.sum()

        return focal_loss


class OntologyMatchingDataset(Dataset):

    def __init__(
        self,
        dataframe,
        tokenizer,
        max_length
    ):

        self.df = dataframe.reset_index(drop=True)

        self.tokenizer = tokenizer

        self.max_length = max_length

    def __len__(self):

        return len(self.df)

    def __getitem__(self, idx):

        row = self.df.iloc[idx]

        src = str(row["SrcLabel"])
        tgt = str(row["TgtLabel"])

        label = int(row["label"])

        encoded = self.tokenizer(
            src,
            tgt,
            padding="max_length",
            truncation=True,
            max_length=self.max_length,
            return_tensors="pt"
        )

        item = {
            "input_ids":
                encoded["input_ids"].squeeze(0),

            "attention_mask":
                encoded["attention_mask"].squeeze(0),

            "labels":
                torch.tensor(label, dtype=torch.long)
        }

        if "token_type_ids" in encoded:

            item["token_type_ids"] = (
                encoded["token_type_ids"]
                .squeeze(0)
            )

        return item


class BiomedicalCrossEncoderTrainer:

    def __init__(
        self,
        config: CrossEncoderTrainingConfig
    ):

        self.config = config

        self.device = (
            "cuda"
            if torch.cuda.is_available()
            else "cpu"
        )

        print(f"\nUsing device: {self.device}")

        self._set_seed()

        self.model = self._load_model()

        self.tokenizer = (
            self.model.tokenizer
        )

        self.history = {
            "val_accuracy": [],
            "val_precision": [],
            "val_recall": [],
            "val_f1": [],
            "val_pr_auc": [],
            "val_roc_auc": []
        }

    def _set_seed(self):

        random.seed(self.config.random_seed)

        np.random.seed(
            self.config.random_seed
        )

        torch.manual_seed(
            self.config.random_seed
        )

        if torch.cuda.is_available():

            torch.cuda.manual_seed_all(
                self.config.random_seed
            )

    def _load_model(self):

        print("\nLoading CrossEncoder...")

        model = CrossEncoder(
            self.config.model_name,
            num_labels=2,
            max_length=self.config.max_length,
            device=self.device
        )

        return model

    def load_dataset(self):

        print("\nLoading dataset...")

        df = pd.read_csv(
            self.config.dataset_path
        )

        required_columns = [
            "SrcEntity",
            "TgtEntity",
            "SrcLabel",
            "TgtLabel",
            "label"
        ]

        for col in required_columns:

            if col not in df.columns:

                raise ValueError(
                    f"Missing column: {col}"
                )

        return df

    def prepare_datasets(self, df):

        print(
            "\nPreparing train/validation split..."
        )

        train_df, val_df = train_test_split(
            df,
            test_size=self.config.validation_split,
            stratify=df["label"],
            random_state=self.config.random_seed
        )

        return train_df, val_df

    def build_dataloaders(
        self,
        train_df,
        val_df
    ):

        train_dataset = OntologyMatchingDataset(
            train_df,
            self.tokenizer,
            self.config.max_length
        )

        val_dataset = OntologyMatchingDataset(
            val_df,
            self.tokenizer,
            self.config.max_length
        )

        train_loader = torch.utils.data.DataLoader(
            train_dataset,
            batch_size=self.config.batch_size,
            shuffle=True,
            num_workers=self.config.num_workers,
            pin_memory=self.config.pin_memory,
            persistent_workers=True
        )

        val_loader = torch.utils.data.DataLoader(
            val_dataset,
            batch_size=self.config.batch_size,
            shuffle=False,
            num_workers=self.config.num_workers,
            pin_memory=self.config.pin_memory,
            persistent_workers=True
        )

        return train_loader, val_loader

    def find_best_threshold(
        self,
        labels,
        probabilities
    ):

        precision, recall, thresholds = (
            precision_recall_curve(
                labels,
                probabilities
            )
        )

        f1_scores = (
            2 * precision * recall
        ) / (
            precision + recall + 1e-8
        )

        best_idx = np.argmax(f1_scores)

        if best_idx >= len(thresholds):
            return 0.5

        return thresholds[best_idx]

    @torch.no_grad()
    def evaluate(
        self,
        val_loader
    ):

        self.model.model.eval()

        all_labels = []
        all_probs = []

        for batch in tqdm(
            val_loader,
            desc="Validation"
        ):

            labels = (
                batch["labels"]
                .cpu()
                .numpy()
            )

            batch = {
                k: v.to(self.device)
                for k, v in batch.items()
                if k != "labels"
            }

            outputs = (
                self.model.model(**batch)
            )

            logits = outputs.logits

            probs = torch.softmax(
                logits,
                dim=1
            )[:, 1]

            all_probs.extend(
                probs.cpu().numpy()
            )

            all_labels.extend(labels)

        all_probs = np.array(all_probs)
        all_labels = np.array(all_labels)

        best_threshold = (
            self.find_best_threshold(
                all_labels,
                all_probs
            )
        )

        predictions = (
            all_probs >= best_threshold
        ).astype(int)

        metrics = {

            "accuracy":
                accuracy_score(
                    all_labels,
                    predictions
                ),

            "precision":
                precision_score(
                    all_labels,
                    predictions,
                    zero_division=0
                ),

            "recall":
                recall_score(
                    all_labels,
                    predictions,
                    zero_division=0
                ),

            "f1":
                f1_score(
                    all_labels,
                    predictions,
                    zero_division=0
                ),

            "roc_auc":
                roc_auc_score(
                    all_labels,
                    all_probs
                ),

            "pr_auc":
                average_precision_score(
                    all_labels,
                    all_probs
                ),

            "threshold":
                float(best_threshold)
        }

        return metrics

    def train(self):

        os.makedirs(
            self.config.output_dir,
            exist_ok=True
        )

        df = self.load_dataset()

        train_df, val_df = (
            self.prepare_datasets(df)
        )

        train_loader, val_loader = (
            self.build_dataloaders(
                train_df,
                val_df
            )
        )

        label_counts = (
            train_df["label"]
            .value_counts()
            .sort_index()
        )

        negatives = label_counts[0]
        positives = label_counts[1]

        total = negatives + positives

        # inverse frequency weighting
        class_weights = torch.tensor(
            [
                total / negatives,
                total / positives
            ],
            dtype=torch.float
        ).to(self.device)

        print("\nClass weights:")
        print(class_weights)

        criterion = WeightedFocalLoss(
            alpha=class_weights,
            gamma=self.config.focal_gamma
        )

        optimizer = torch.optim.AdamW(
            self.model.model.parameters(),
            lr=self.config.learning_rate,
            weight_decay=self.config.weight_decay
        )

        scaler = torch.cuda.amp.GradScaler(
            enabled=(
                self.device == "cuda"
                and self.config.fp16
            )
        )

        total_steps = (
            len(train_loader)
            * self.config.epochs
        )

        warmup_steps = int(
            total_steps * 0.1
        )

        scheduler = (
            torch.optim.lr_scheduler.CosineAnnealingLR(
                optimizer,
                T_max=total_steps
            )
        )

        best_pr_auc = 0.0

        patience_counter = 0

        best_model_path = os.path.join(
            self.config.output_dir,
            "best_model"
        )

        print("\nStarting training...")

        global_step = 0

        for epoch in range(
            self.config.epochs
        ):

            print(
                f"\nEpoch "
                f"{epoch + 1}/"
                f"{self.config.epochs}"
            )

            self.model.model.train()

            optimizer.zero_grad()

            running_loss = 0.0

            progress_bar = tqdm(
                train_loader,
                desc=f"Training Epoch {epoch+1}"
            )

            for step, batch in enumerate(
                progress_bar
            ):

                labels = (
                    batch["labels"]
                    .to(self.device)
                )

                batch = {
                    k: v.to(self.device)
                    for k, v in batch.items()
                    if k != "labels"
                }

                with torch.cuda.amp.autocast(
                    enabled=(
                        self.device == "cuda"
                        and self.config.fp16
                    )
                ):

                    outputs = (
                        self.model.model(**batch)
                    )

                    logits = outputs.logits

                    loss = criterion(
                        logits,
                        labels
                    )

                    loss = (
                        loss
                        / self.config.gradient_accumulation_steps
                    )

                scaler.scale(loss).backward()

                if (
                    (step + 1)
#                     % self.config.gradient_accumulation_steps
                    == 0
                ):

                    scaler.step(optimizer)

                    scaler.update()

                    optimizer.zero_grad()

                    scheduler.step()

                    global_step += 1

                running_loss += loss.item()

                progress_bar.set_postfix({
                    "loss":
                        running_loss / (step + 1)
                })

            metrics = self.evaluate(
                val_loader
            )

            print("\nValidation Metrics:")

            print(
                json.dumps(
                    metrics,
                    indent=2
                )
            )

            for key in self.history:

                metric_name = key.replace(
                    "val_",
                    ""
                )

                self.history[key].append(
                    metrics[metric_name]
                )

            current_pr_auc = (
                metrics["pr_auc"]
            )

            if current_pr_auc > best_pr_auc:

                best_pr_auc = current_pr_auc

                patience_counter = 0

                print(
                    "\nNew best model found."
                )

                self.model.save(
                    best_model_path
                )

            else:

                patience_counter += 1

                print(
                    f"\nNo improvement. "
                    f"Patience: "
                    f"{patience_counter}/"
                    f"{self.config.early_stopping_patience}"
                )

            if (
                patience_counter
                >= self.config.early_stopping_patience
            ):

                print(
                    "\nEarly stopping triggered."
                )

                break

        self.save_history()

        print(
            f"\nTraining completed.\n"
            f"Best model saved to:\n"
            f"{best_model_path}"
        )

    def save_history(self):

        history_path = os.path.join(
            self.config.output_dir,
            "training_history.json"
        )

        with open(history_path, "w") as f:

            json.dump(
                self.history,
                f,
                indent=2
            )

        print(
            f"\nTraining history saved to:\n"
            f"{history_path}"
        )

"""## (LM) BERT (Cross-Encoder)"""

# Commented out IPython magic to ensure Python compatibility.
import os
import json
import random
import numpy as np
import pandas as pd

from dataclasses import dataclass
from typing import Dict

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    precision_recall_curve
)

from tqdm.auto import tqdm

from sentence_transformers.cross_encoder import CrossEncoder


@dataclass
class CrossEncoderTrainingConfig:

    model_name: str
    dataset_path: str
    output_dir: str

    batch_size: int = 64
    epochs: int = 5
    learning_rate: float = 2e-5
    max_length: int = 512

    validation_split: float = 0.2
    random_seed: int = 42

    early_stopping_patience: int = 2

    gradient_accumulation_steps: int = 1

    weight_decay: float = 0.01

    num_workers: int = 4

    # focal loss
    focal_gamma: float = 2.0

    # optimized automatically from class distribution
    focal_alpha: float = None

    threshold: float = 0.5

    fp16: bool = True

    pin_memory: bool = True


class WeightedFocalLoss(nn.Module):

    """
    Multi-class focal loss for:
        num_labels = 2

    Uses CrossEntropy internally.
    """

    def __init__(
        self,
        alpha=None,
        gamma=2.0,
        reduction="mean"
    ):
        super().__init__()

        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction

    def forward(
        self,
        logits,
        targets
    ):

        targets = targets.long()

        ce_loss = F.cross_entropy(
            logits,
            targets,
            reduction="none",
            weight=self.alpha
        )

        pt = torch.exp(-ce_loss)

        focal_loss = (
            (1 - pt) ** self.gamma
        ) * ce_loss

        if self.reduction == "mean":
            return focal_loss.mean()

        elif self.reduction == "sum":
            return focal_loss.sum()

        return focal_loss


class OntologyMatchingDataset(Dataset):

    def __init__(
        self,
        dataframe,
        tokenizer,
        max_length
    ):

        self.df = dataframe.reset_index(drop=True)

        self.tokenizer = tokenizer

        self.max_length = max_length

    def __len__(self):

        return len(self.df)

    def __getitem__(self, idx):

        row = self.df.iloc[idx]

        src = str(row["SrcLabel"])
        tgt = str(row["TgtLabel"])

        label = int(row["label"])

        encoded = self.tokenizer(
            src,
            tgt,
            padding="max_length",
            truncation=True,
            max_length=self.max_length,
            return_tensors="pt"
        )

        item = {
            "input_ids":
                encoded["input_ids"].squeeze(0),

            "attention_mask":
                encoded["attention_mask"].squeeze(0),

            "labels":
                torch.tensor(label, dtype=torch.long)
        }

        if "token_type_ids" in encoded:

            item["token_type_ids"] = (
                encoded["token_type_ids"]
                .squeeze(0)
            )

        return item


class BiomedicalCrossEncoderTrainer:

    def __init__(
        self,
        config: CrossEncoderTrainingConfig
    ):

        self.config = config

        self.device = (
            "cuda"
            if torch.cuda.is_available()
            else "cpu"
        )

        print(f"\nUsing device: {self.device}")

        self._set_seed()

        self.model = self._load_model()

        self.tokenizer = (
            self.model.tokenizer
        )

        self.history = {
            "val_accuracy": [],
            "val_precision": [],
            "val_recall": [],
            "val_f1": [],
            "val_pr_auc": [],
            "val_roc_auc": []
        }

    def _set_seed(self):

        random.seed(self.config.random_seed)

        np.random.seed(
            self.config.random_seed
        )

        torch.manual_seed(
            self.config.random_seed
        )

        if torch.cuda.is_available():

            torch.cuda.manual_seed_all(
                self.config.random_seed
            )

    def _load_model(self):

        print("\nLoading CrossEncoder...")

        model = CrossEncoder(
            self.config.model_name,
            num_labels=2,
            max_length=self.config.max_length,
            device=self.device
        )

        return model

    def validate_dataset(self, df):

        required_columns = [
            "SrcEntity",
            "TgtEntity",
            "SrcLabel",
            "TgtLabel",
            "label"
        ]

        for col in required_columns:

            if col not in df.columns:

                raise ValueError(
                    f"Missing column: {col}"
                )

    def build_dataloaders(
        self,
        train_df,
        val_df
    ):

        train_dataset = OntologyMatchingDataset(
            train_df,
            self.tokenizer,
            self.config.max_length
        )

        val_dataset = OntologyMatchingDataset(
            val_df,
            self.tokenizer,
            self.config.max_length
        )

        train_loader = torch.utils.data.DataLoader(
            train_dataset,
            batch_size=self.config.batch_size,
            shuffle=True,
            num_workers=self.config.num_workers,
            pin_memory=self.config.pin_memory,
            persistent_workers=True
        )

        val_loader = torch.utils.data.DataLoader(
            val_dataset,
            batch_size=self.config.batch_size,
            shuffle=False,
            num_workers=self.config.num_workers,
            pin_memory=self.config.pin_memory,
            persistent_workers=True
        )

        return train_loader, val_loader

    def find_best_threshold(
        self,
        labels,
        probabilities
    ):

        precision, recall, thresholds = (
            precision_recall_curve(
                labels,
                probabilities
            )
        )

        f1_scores = (
            2 * precision * recall
        ) / (
            precision + recall + 1e-8
        )

        best_idx = np.argmax(f1_scores)

        if best_idx >= len(thresholds):
            return 0.5

        return thresholds[best_idx]

    @torch.no_grad()
    def evaluate(
        self,
        val_loader
    ):

        self.model.model.eval()

        all_labels = []
        all_probs = []

        for batch in tqdm(
            val_loader,
            desc="Validation"
        ):

            labels = (
                batch["labels"]
                .cpu()
                .numpy()
            )

            batch = {
                k: v.to(self.device)
                for k, v in batch.items()
                if k != "labels"
            }

            outputs = (
                self.model.model(**batch)
            )

            logits = outputs.logits

            probs = torch.softmax(
                logits,
                dim=1
            )[:, 1]

            all_probs.extend(
                probs.cpu().numpy()
            )

            all_labels.extend(labels)

        all_probs = np.array(all_probs)
        all_labels = np.array(all_labels)

        best_threshold = (
            self.find_best_threshold(
                all_labels,
                all_probs
            )
        )

        predictions = (
            all_probs >= best_threshold
        ).astype(int)

        metrics = {

            "accuracy":
                accuracy_score(
                    all_labels,
                    predictions
                ),

            "precision":
                precision_score(
                    all_labels,
                    predictions,
                    zero_division=0
                ),

            "recall":
                recall_score(
                    all_labels,
                    predictions,
                    zero_division=0
                ),

            "f1":
                f1_score(
                    all_labels,
                    predictions,
                    zero_division=0
                ),

            "roc_auc":
                roc_auc_score(
                    all_labels,
                    all_probs
                ),

            "pr_auc":
                average_precision_score(
                    all_labels,
                    all_probs
                ),

            "threshold":
                float(best_threshold)
        }

        return metrics

    def train(
        self,
        train_df,
        val_df
    ):

        os.makedirs(
            self.config.output_dir,
            exist_ok=True
        )

        self.validate_dataset(train_df)
        self.validate_dataset(val_df)

        train_loader, val_loader = (
            self.build_dataloaders(
                train_df,
                val_df
            )
        )

        label_counts = (
            train_df["label"]
            .value_counts()
            .sort_index()
        )

        negatives = label_counts[0]
        positives = label_counts[1]

        total = negatives + positives

        # inverse frequency weighting
        class_weights = torch.tensor(
            [
                total / negatives,
                total / positives
            ],
            dtype=torch.float
        ).to(self.device)

        print("\nClass weights:")
        print(class_weights)

        criterion = WeightedFocalLoss(
            alpha=class_weights,
            gamma=self.config.focal_gamma
        )

        optimizer = torch.optim.AdamW(
            self.model.model.parameters(),
            lr=self.config.learning_rate,
            weight_decay=self.config.weight_decay
        )

        scaler = torch.cuda.amp.GradScaler(
            enabled=(
                self.device == "cuda"
                and self.config.fp16
            )
        )

        total_steps = (
            len(train_loader)
            * self.config.epochs
        )

        warmup_steps = int(
            total_steps * 0.1
        )

        scheduler = (
            torch.optim.lr_scheduler.CosineAnnealingLR(
                optimizer,
                T_max=total_steps
            )
        )

        best_pr_auc = 0.0

        patience_counter = 0

        best_model_path = os.path.join(
            self.config.output_dir,
            "best_model"
        )

        print("\nStarting training...")

        global_step = 0

        for epoch in range(
            self.config.epochs
        ):

            print(
                f"\nEpoch "
                f"{epoch + 1}/"
                f"{self.config.epochs}"
            )

            self.model.model.train()

            optimizer.zero_grad()

            running_loss = 0.0

            progress_bar = tqdm(
                train_loader,
                desc=f"Training Epoch {epoch+1}"
            )

            for step, batch in enumerate(
                progress_bar
            ):

                labels = (
                    batch["labels"]
                    .to(self.device)
                )

                batch = {
                    k: v.to(self.device)
                    for k, v in batch.items()
                    if k != "labels"
                }

                with torch.cuda.amp.autocast(
                    enabled=(
                        self.device == "cuda"
                        and self.config.fp16
                    )
                ):

                    outputs = (
                        self.model.model(**batch)
                    )

                    logits = outputs.logits

                    loss = criterion(
                        logits,
                        labels
                    )

                    loss = (
                        loss
                        / self.config.gradient_accumulation_steps
                    )

                scaler.scale(loss).backward()

                if (
                    (step + 1)
#                     % self.config.gradient_accumulation_steps
                    == 0
                ):

                    scaler.step(optimizer)

                    scaler.update()

                    optimizer.zero_grad()

                    scheduler.step()

                    global_step += 1

                running_loss += loss.item()

                progress_bar.set_postfix({
                    "loss":
                        running_loss / (step + 1)
                })

            metrics = self.evaluate(
                val_loader
            )

            print("\nValidation Metrics:")

            print(
                json.dumps(
                    metrics,
                    indent=2
                )
            )

            for key in self.history:

                metric_name = key.replace(
                    "val_",
                    ""
                )

                self.history[key].append(
                    metrics[metric_name]
                )

            current_pr_auc = (
                metrics["pr_auc"]
            )

            if current_pr_auc > best_pr_auc:

                best_pr_auc = current_pr_auc

                patience_counter = 0

                print(
                    "\nNew best model found."
                )

                self.model.save(
                    best_model_path
                )

            else:

                patience_counter += 1

                print(
                    f"\nNo improvement. "
                    f"Patience: "
                    f"{patience_counter}/"
                    f"{self.config.early_stopping_patience}"
                )

            if (
                patience_counter
                >= self.config.early_stopping_patience
            ):

                print(
                    "\nEarly stopping triggered."
                )

                break

        self.save_history()

        print(
            f"\nTraining completed.\n"
            f"Best model saved to:\n"
            f"{best_model_path}"
        )

    def save_history(self):

        history_path = os.path.join(
            self.config.output_dir,
            "training_history.json"
        )

        with open(history_path, "w") as f:

            json.dump(
                self.history,
                f,
                indent=2
            )

        print(
            f"\nTraining history saved to:\n"
            f"{history_path}"
        )

"""## SBERT (Sentence Transformer)"""

import os
import json
import random
import numpy as np
import pandas as pd

from dataclasses import dataclass

import torch
from torch.utils.data import DataLoader

from sklearn.model_selection import train_test_split

from sentence_transformers import (
    SentenceTransformer,
    InputExample,
    losses,
    evaluation
)

from tqdm.auto import tqdm


@dataclass
class TrainingConfig:
    model_name: str
    dataset_path: str
    output_dir: str

    batch_size: int = 128
    epochs: int = 5
    learning_rate: float = 2e-5
    max_seq_length: int = 64

    validation_split: float = 0.2
    random_seed: int = 42

    num_workers: int = 4
    fp16: bool = True
    warmup_ratio: float = 0.1

    evaluation_steps: int = 1000
    early_stopping_patience: int = 2


class BiomedicalSentenceTransformerTrainer:

    def __init__(self, config: TrainingConfig):

        self.config = config

        self.device = "cuda" if torch.cuda.is_available() else "cpu"

        print(f"\nUsing device: {self.device}")

        self._set_seed()
        self.model = self._load_model()

        self.history = {
            "val_recall@1": [],
            "val_recall@10": [],
            "val_mrr": []
        }

    def _set_seed(self):
        random.seed(self.config.random_seed)
        np.random.seed(self.config.random_seed)
        torch.manual_seed(self.config.random_seed)

        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(self.config.random_seed)

    def _load_model(self):

        print("\nLoading SentenceTransformer...")

        model = SentenceTransformer(
            self.config.model_name,
            device=self.device
        )

        model.max_seq_length = self.config.max_seq_length

        return model

    def load_dataset(self):

        df = pd.read_csv(self.config.dataset_path)

        required = ["SrcLabel", "TgtLabel"]

        for c in required:
            if c not in df.columns:
                raise ValueError(f"Missing column: {c}")

        return df

    def prepare_split(self, df):

        train_df, val_df = train_test_split(
            df,
            test_size=self.config.validation_split,
            random_state=self.config.random_seed
        )

        return train_df, val_df

    def build_input_examples(self, df):

        examples = []

        for _, row in tqdm(df.iterrows(), total=len(df)):

            examples.append(
                InputExample(
                    texts=[
                        str(row["SrcLabel"]),
                        str(row["TgtLabel"])
                    ]
                )
            )

        return examples

    @torch.no_grad()
    def evaluate(self, model, val_df):

        model.eval()

        src = val_df["SrcLabel"].astype(str).tolist()
        tgt = val_df["TgtLabel"].astype(str).tolist()

        src_emb = model.encode(
            src,
            batch_size=self.config.batch_size,
            convert_to_tensor=True,
            normalize_embeddings=True,
            show_progress_bar=False
        )

        tgt_emb = model.encode(
            tgt,
            batch_size=self.config.batch_size,
            convert_to_tensor=True,
            normalize_embeddings=True,
            show_progress_bar=False
        )

        sim = src_emb @ tgt_emb.T
        sim = sim.cpu().numpy()

        recall_at_1 = 0
        recall_at_10 = 0
        mrr = 0.0

        for i in range(len(src)):

            ranked = np.argsort(-sim[i])

            if ranked[0] == i:
                recall_at_1 += 1

            if i in ranked[:10]:
                recall_at_10 += 1

            rank = np.where(ranked == i)[0][0] + 1
            mrr += 1.0 / rank

        n = len(src)

        return {
            "recall@1": recall_at_1 / n,
            "recall@10": recall_at_10 / n,
            "mrr": mrr / n
        }

    def train(self):

        os.makedirs(self.config.output_dir, exist_ok=True)

        df = self.load_dataset()
        train_df, val_df = self.prepare_split(df)

        train_examples = self.build_input_examples(train_df)
        val_examples = self.build_input_examples(val_df)

        train_loader = DataLoader(
            train_examples,
            shuffle=True,
            batch_size=self.config.batch_size,
            num_workers=self.config.num_workers,
            pin_memory=True
        )

        train_loss = losses.MultipleNegativesRankingLoss(
            model=self.model
        )

        queries = {
            str(i): str(row["SrcLabel"])
            for i, row in val_df.iterrows()
        }

        corpus = {
            str(i): str(row["TgtLabel"])
            for i, row in val_df.iterrows()
        }

        relevant_docs = {
            str(i): {str(i)}
            for i in val_df.index
        }

        evaluator = evaluation.InformationRetrievalEvaluator(
            queries=queries,
            corpus=corpus,
            relevant_docs=relevant_docs,
            name="val"
        )

        total_steps = len(train_loader) * self.config.epochs
        warmup_steps = int(total_steps * self.config.warmup_ratio)

        best_score = 0
        patience = 0

        best_path = os.path.join(self.config.output_dir, "best_model")

        print("\nStarting training...")

        for epoch in range(self.config.epochs):

            print(f"\nEpoch {epoch+1}/{self.config.epochs}")

            model = self.model

            model.fit(
                train_objectives=[(train_loader, train_loss)],
                epochs=1,
                warmup_steps=warmup_steps,
                optimizer_params={"lr": self.config.learning_rate},
                output_path=best_path,
                save_best_model=True,
                show_progress_bar=True,
                use_amp=self.config.fp16,
            )

            metrics = self.evaluate(self.model, val_df)

            print("\nValidation metrics:")
            print(json.dumps(metrics, indent=2))

            score = metrics["mrr"]

            if score > best_score:
                best_score = score
                patience = 0
                self.model.save(best_path)
                print("\nNew best model")
            else:
                patience += 1
                print(f"\nNo improvement: {patience}/{self.config.early_stopping_patience}")

            if patience >= self.config.early_stopping_patience:
                print("\nEarly stopping triggered")
                break

        print(f"\nTraining complete. Best model: {best_path}")

"""## (LM) SBERT (Sentence Transformer)"""

import os
import json
import random
import numpy as np
import pandas as pd

from dataclasses import dataclass

import torch
from torch.utils.data import DataLoader

from sklearn.model_selection import train_test_split

from sentence_transformers import (
    SentenceTransformer,
    InputExample,
    losses,
    evaluation
)

from tqdm.auto import tqdm


@dataclass
class TrainingConfig:
    model_name: str
    dataset_path: str
    output_dir: str

    batch_size: int = 128
    epochs: int = 5
    learning_rate: float = 2e-5
    max_seq_length: int = 64

    validation_split: float = 0.2
    random_seed: int = 42

    num_workers: int = 4
    fp16: bool = True
    warmup_ratio: float = 0.1

    evaluation_steps: int = 1000
    early_stopping_patience: int = 2


class BiomedicalSentenceTransformerTrainer:

    def __init__(self, config: TrainingConfig):

        self.config = config

        self.device = "cuda" if torch.cuda.is_available() else "cpu"

        print(f"\nUsing device: {self.device}")

        self._set_seed()
        self.model = self._load_model()

        self.history = {
            "val_recall@1": [],
            "val_recall@10": [],
            "val_mrr": []
        }

    def _set_seed(self):
        random.seed(self.config.random_seed)
        np.random.seed(self.config.random_seed)
        torch.manual_seed(self.config.random_seed)

        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(self.config.random_seed)

    def _load_model(self):

        print("\nLoading SentenceTransformer...")

        model = SentenceTransformer(
            self.config.model_name,
            device=self.device
        )

        model.max_seq_length = self.config.max_seq_length

        return model

    def validate_dataset(self, df):

      required = ["SrcLabel", "TgtLabel"]

      for c in required:

          if c not in df.columns:

              raise ValueError(
                  f"Missing column: {c}"
              )

    def build_input_examples(self, df):

        examples = []

        for _, row in tqdm(df.iterrows(), total=len(df)):

            examples.append(
                InputExample(
                    texts=[
                        str(row["SrcLabel"]),
                        str(row["TgtLabel"])
                    ]
                )
            )

        return examples

    @torch.no_grad()
    def evaluate(self, model, val_df):

        model.eval()

        src = val_df["SrcLabel"].astype(str).tolist()
        tgt = val_df["TgtLabel"].astype(str).tolist()

        src_emb = model.encode(
            src,
            batch_size=self.config.batch_size,
            convert_to_tensor=True,
            normalize_embeddings=True,
            show_progress_bar=False
        )

        tgt_emb = model.encode(
            tgt,
            batch_size=self.config.batch_size,
            convert_to_tensor=True,
            normalize_embeddings=True,
            show_progress_bar=False
        )

        sim = src_emb @ tgt_emb.T
        sim = sim.cpu().numpy()

        recall_at_1 = 0
        recall_at_10 = 0
        mrr = 0.0

        for i in range(len(src)):

            ranked = np.argsort(-sim[i])

            if ranked[0] == i:
                recall_at_1 += 1

            if i in ranked[:10]:
                recall_at_10 += 1

            rank = np.where(ranked == i)[0][0] + 1
            mrr += 1.0 / rank

        n = len(src)

        return {
            "recall@1": recall_at_1 / n,
            "recall@10": recall_at_10 / n,
            "mrr": mrr / n
        }

    def train(
        self,
        train_df,
        val_df
    ):

        os.makedirs(self.config.output_dir, exist_ok=True)

        self.validate_dataset(train_df)
        self.validate_dataset(val_df)

        train_examples = self.build_input_examples(train_df)
        val_examples = self.build_input_examples(val_df)

        train_loader = DataLoader(
            train_examples,
            shuffle=True,
            batch_size=self.config.batch_size,
            num_workers=self.config.num_workers,
            pin_memory=True
        )

        train_loss = losses.MultipleNegativesRankingLoss(
            model=self.model
        )

        queries = {
            str(i): str(row["SrcLabel"])
            for i, row in val_df.iterrows()
        }

        corpus = {
            str(i): str(row["TgtLabel"])
            for i, row in val_df.iterrows()
        }

        relevant_docs = {
            str(i): {str(i)}
            for i in val_df.index
        }

        evaluator = evaluation.InformationRetrievalEvaluator(
            queries=queries,
            corpus=corpus,
            relevant_docs=relevant_docs,
            name="val"
        )

        total_steps = len(train_loader) * self.config.epochs
        warmup_steps = int(total_steps * self.config.warmup_ratio)

        best_score = 0
        patience = 0

        best_path = os.path.join(self.config.output_dir, "best_model")

        print("\nStarting training...")

        for epoch in range(self.config.epochs):

            print(f"\nEpoch {epoch+1}/{self.config.epochs}")

            model = self.model

            model.fit(
                train_objectives=[(train_loader, train_loss)],
                epochs=1,
                warmup_steps=warmup_steps,
                optimizer_params={"lr": self.config.learning_rate},
                output_path=best_path,
                save_best_model=True,
                show_progress_bar=True,
                use_amp=self.config.fp16,
            )

            metrics = self.evaluate(self.model, val_df)

            print("\nValidation metrics:")
            print(json.dumps(metrics, indent=2))

            score = metrics["mrr"]

            if score > best_score:
                best_score = score
                patience = 0
                self.model.save(best_path)
                print("\nNew best model")
            else:
                patience += 1
                print(f"\nNo improvement: {patience}/{self.config.early_stopping_patience}")

            if patience >= self.config.early_stopping_patience:
                print("\nEarly stopping triggered")
                break

        print(f"\nTraining complete. Best model: {best_path}")

"""# Matching

## Lexical

### TFIDF
"""

def tfidf_candidate_selection(
    df_src,
    df_tgt,
    top_k=15,
    src_label_col="SrcLabel",
    tgt_label_col="TgtLabel",
    src_entity_col="SrcEntity",
    tgt_entity_col="TgtEntity"
):
    def normalize(text):
        return str(text).lower().strip()

    src_labels = df_src[src_label_col].apply(normalize).tolist()
    tgt_labels = df_tgt[tgt_label_col].apply(normalize).tolist()

    vectorizer = TfidfVectorizer(
        lowercase=True,
        stop_words="english",
        ngram_range=(1, 2)
    )

    all_labels = src_labels + tgt_labels
    X_all = vectorizer.fit_transform(all_labels)

    X_src = X_all[:len(src_labels)]
    X_tgt = X_all[len(src_labels):]

    sim_matrix = cosine_similarity(X_src, X_tgt)

    rows = []

    for i in tqdm(range(sim_matrix.shape[0]), total=sim_matrix.shape[0], desc="Selecting Candidates"):
        # fast top-k selection
        top_idx = np.argpartition(sim_matrix[i], -top_k)[-top_k:]
        top_idx = top_idx[np.argsort(sim_matrix[i][top_idx])[::-1]]

        for j in top_idx:
            rows.append({
                "SrcEntity": df_src.iloc[i][src_entity_col],
                "TgtEntity": df_tgt.iloc[j][tgt_entity_col],
                "SrcLabel": df_src.iloc[i][src_label_col],
                "TgtLabel": df_tgt.iloc[j][tgt_label_col],
                "tfidf score": float(sim_matrix[i][j])
            })

    return pd.DataFrame(rows)

"""## Model Matching

### SBERT (ST)
"""

import numpy as np
import pandas as pd
import torch

from dataclasses import dataclass
from tqdm.auto import tqdm

from sentence_transformers import SentenceTransformer


@dataclass
class RetrievalConfig:
    model_path: str
    batch_size: int = 64
    top_k: int = 10
    normalize_embeddings: bool = True
    device: str = None


class OntologyTopKRetriever:

    def __init__(self, config: RetrievalConfig):

        self.config = config

        self.device = (
            config.device
            if config.device
            else ("cuda" if torch.cuda.is_available() else "cpu")
        )

        print(f"\nUsing device: {self.device}")

        self.model = SentenceTransformer(
            config.model_path,
            device=self.device
        )

        self.tgt_embeddings = None
        self.tgt_df = None

    def encode_targets(self, df_tgt: pd.DataFrame):

        print("\nEncoding target ontology...")

        self.tgt_df = df_tgt.reset_index(drop=True)

        tgt_texts = self.tgt_df["TgtLabel"].astype(str).tolist()

        self.tgt_embeddings = self.model.encode(
            tgt_texts,
            batch_size=self.config.batch_size,
            convert_to_tensor=True,
            show_progress_bar=True,
            normalize_embeddings=self.config.normalize_embeddings
        )

        print(f"Target embeddings shape: {self.tgt_embeddings.shape}")

    def retrieve(self, df_src: pd.DataFrame) -> pd.DataFrame:

        if self.tgt_embeddings is None:
            raise ValueError("Call encode_targets() first.")

        print("\nEncoding source ontology...")

        src_labels = df_src["SrcLabel"].astype(str).tolist()
        src_entities = df_src["SrcEntity"].astype(str).tolist()

        src_embeddings = self.model.encode(
            src_labels,
            batch_size=self.config.batch_size,
            convert_to_tensor=True,
            show_progress_bar=True,
            normalize_embeddings=self.config.normalize_embeddings
        )

        print("\nComputing similarity matrix...")

        similarity_matrix = torch.matmul(
            src_embeddings,
            self.tgt_embeddings.T
        )

        top_k = self.config.top_k

        print("\nExtracting Top-K pairs into DataFrame...")

        rows = []

        for i in tqdm(range(len(df_src))):

            scores, indices = torch.topk(
                similarity_matrix[i],
                k=top_k
            )

            src_entity = src_entities[i]
            src_label = df_src.iloc[i]["SrcLabel"]

            for score, idx in zip(scores, indices):
                rows.append({
                    "SrcEntity": src_entity,
                    "SrcLabel": src_label,
                    "TgtEntity": self.tgt_df.iloc[int(idx.item())]["TgtEntity"],
                    "TgtLabel": self.tgt_df.iloc[int(idx.item())]["TgtLabel"],
                    "score": float(score)
                })

        return pd.DataFrame(rows)

    def run(self, df_src: pd.DataFrame, df_tgt: pd.DataFrame) -> pd.DataFrame:

        self.encode_targets(df_tgt)

        return self.retrieve(df_src)

"""### BERT (CE)"""

import numpy as np
import pandas as pd
import torch

from dataclasses import dataclass
from tqdm.auto import tqdm

from sentence_transformers.cross_encoder import CrossEncoder


@dataclass
class CrossEncoderRerankerConfig:

    model_path: str

    batch_size: int = 32

    max_length: int = 512

    device: str = None


class CrossEncoderOntologyReranker:

    def __init__(
        self,
        config: CrossEncoderRerankerConfig
    ):

        self.config = config

        self.device = (
            config.device
            if config.device
            else (
                "cuda"
                if torch.cuda.is_available()
                else "cpu"
            )
        )

        print(f"\nUsing device: {self.device}")

        self.model = CrossEncoder(
            config.model_path,
            max_length=config.max_length,
            device=self.device
        )

    def rerank(
        self,
        candidates_df: pd.DataFrame
    ) -> pd.DataFrame:

        required_columns = [
            "SrcEntity",
            "TgtEntity",
            "SrcLabel",
            "TgtLabel"
        ]

        for col in required_columns:

            if col not in candidates_df.columns:

                raise ValueError(
                    f"Missing column: {col}"
                )

        print(
            "\nPreparing sentence pairs..."
        )

        sentence_pairs = list(zip(
            candidates_df["SrcLabel"].astype(str),
            candidates_df["TgtLabel"].astype(str)
        ))

        print(
            "\nRunning cross-encoder scoring..."
        )

        scores = self.model.predict(
            sentence_pairs,
            batch_size=self.config.batch_size,
            show_progress_bar=True,
            apply_softmax=True
        )

        print(f"{scores.tolist()[:5]=}")

        # positive-class probability
        scores = scores[:, 1]

        reranked_df = candidates_df.copy()

        reranked_df["cross_encoder_score"] = (
            scores
        )

        reranked_df = (
            reranked_df
            .sort_values(
                by=[
                    "SrcEntity",
                    "cross_encoder_score"
                ],
                ascending=[True, False]
            )
            .reset_index(drop=True)
        )

        reranked_df["rank"] = (
            reranked_df
            .groupby("SrcEntity")
            .cumcount() + 1
        )

        return reranked_df

"""## Alignments

### Adaptive top-k
"""

import numpy as np
import pandas as pd
from dataclasses import dataclass
from tqdm.auto import tqdm


@dataclass
class AdaptiveTopKConfig:
    score_col: str = "score"   # score column
    tau_min: float = 0.75      # absolute threshold
    delta: float = 0.05        # score drop threshold
    ratio_min: float = 0.90    # relative confidence threshold


class AdaptiveTopKMatcher:

    def __init__(self, config: AdaptiveTopKConfig):
        self.config = config

    def filter(self, df: pd.DataFrame) -> pd.DataFrame:

        print("\nApplying adaptive Top-K filtering...")

        results = []

        grouped = df.groupby("SrcEntity")

        for src_entity, group in tqdm(grouped):

            group = group.sort_values(
                self.config.score_col,
                ascending=False
            ).reset_index(drop=True)

            best_score = group.iloc[0][self.config.score_col]

            kept = []

            for i in range(len(group)):

                score = group.iloc[i][self.config.score_col]

                if score < self.config.tau_min:
                    break

                if score / best_score < self.config.ratio_min:
                    break

                if i > 0:
                    prev_score = group.iloc[i - 1][self.config.score_col]
                    if (prev_score - score) > self.config.delta:
                        break

                kept.append(group.iloc[i])

            results.extend(kept)

        return pd.DataFrame(results)

"""# Evaluation

## Recall@1 (ST)
"""

def recall_at_1_sentence_transformer(
    alignments_df,
    gold_df
):
    gold_pairs = set(zip(
        gold_df["SrcEntity"],
        gold_df["TgtEntity"]
    ))

    ranked = (
        alignments_df
        .sort_values(
            ["SrcEntity", "score"],
            ascending=[True, False]
        )
    )

    top1 = (
        ranked
        .groupby("SrcEntity")
        .head(1)
    )

    hits = 0

    for _, row in top1.iterrows():

        pair = (
            row["SrcEntity"],
            row["TgtEntity"]
        )

        if pair in gold_pairs:
            hits += 1

    total = (
        gold_df["SrcEntity"]
        .nunique()
    )

    recall1 = hits / total

    return recall1

"""## Recall@1 (CE)"""

def recall_at_1(
    reranked_df,
    gold_df
):

    gold_pairs = set(zip(
        gold_df["SrcEntity"],
        gold_df["TgtEntity"]
    ))

    top1 = (
        reranked_df
        .sort_values(
            ["SrcEntity", "rank"]
        )
        .groupby("SrcEntity")
        .head(1)
    )

    hits = 0

    for _, row in top1.iterrows():

        pair = (
            row["SrcEntity"],
            row["TgtEntity"]
        )

        if pair in gold_pairs:
            hits += 1

    total_queries = (
        reranked_df["SrcEntity"]
        .nunique()
    )

    return hits / total_queries

"""## Global Matching Eval"""

def PipelineEvaluation(df_matches, df_references, display_report=True, report_name=""):
    matches = set(
        (str(row['SrcEntity']), str(row['TgtEntity']))
        for row_idx, row in df_matches.iterrows()
    )
    gt = set(
        (str(row['SrcEntity']), str(row['TgtEntity']))
        for row_idx, row in df_references.iterrows()
    )

    tp_set = matches.intersection(gt)

    FP = matches - gt
    FN = gt - matches

    pd.DataFrame(tp_set, columns=['SrcEntity', 'TgtEntity']).to_csv(r"/content/TP.csv")
    pd.DataFrame(FP, columns=['SrcEntity', 'TgtEntity']).to_csv(r"/content/FP.csv")
    pd.DataFrame(FN, columns=['SrcEntity', 'TgtEntity']).to_csv(r"/content/FN.csv")

    tp = len(tp_set)
    fp = len(matches - gt)
    fn = len(gt - matches)

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0

    lines = [
        "-" * 30,
        f"EVALUATION REPORT : " + report_name,
        "-" * 30,
        f"Ground Truth Matches:  {len(gt)}",
        f"Predicted Matches:     {len(matches)}",
        f"True Positives (TP):   {tp}",
        f"False Positives (FP):  {fp}",
        f"False Negatives (FN):  {fn}",
        "-" * 30,
        f"Precision:             {precision:.4f}",
        f"Recall:                {recall:.4f}",
        f"F1 Score:              {f1:.4f}",
        "-" * 30,
        f"=== END REPORT ===\n"
    ]

    if display_report:
      for line in lines:
          print(line)

    return {
        "Ground Truth Matches": len(gt),
        "Predicted Matches": len(matches),
        "TP": tp,
        "FP": fp,
        "FN": fn,
        "P": precision, "R": recall, "F1": f1
    }

"""## Local Matching Eval"""

def evaluate_retrieval(
    results_df: pd.DataFrame,
    ground_truth_df: pd.DataFrame
):
    gt_map = dict(
        zip(
            ground_truth_df["SrcEntity"],
            ground_truth_df["TgtEntity (True)"]
        )
    )

    top1 = results_df[results_df["rank"] == 1]

    top1_map = dict(
        zip(
            top1["SrcEntity"],
            top1["TgtEntity"]
        )
    )

    all_sources = set(gt_map.keys())

    tp = 0
    fp = 0
    fn = 0

    recall_at_1_hits = 0

    for src in all_sources:

        true_tgt = gt_map[src]

        pred_tgt = top1_map.get(src, None)

        # Recall@1
        if pred_tgt == true_tgt:
            recall_at_1_hits += 1
            tp += 1
        else:
            fp += 1
            fn += 1

    precision = tp / (tp + fp + 1e-9)
    recall = tp / (tp + fn + 1e-9)
    f1 = (2 * precision * recall) / (precision + recall + 1e-9)
    recall_at_1 = recall_at_1_hits / len(all_sources)

    return {
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "recall@1": recall_at_1
    }

"""# Main

## Inputs
"""

# SNOMED-NCIT (Pharm)
SRC_ENTITIES_FILE = r"/content/snomed_ncit_pharm_src_entities.csv"
TGT_ENTITIES_FILE = r"/content/snomed_ncit_pharm_tgt_entities.csv"

# NCIT-DOID
# SRC_ENTITIES_FILE = r"/content/ncit_doid_src_entities.csv"
# TGT_ENTITIES_FILE = r"/content/ncit_doid_tgt_entities.csv"

LABEL_COL = "EntityLabel (Extended)"

"""# ---

## Obtaining Source and Target Ontology Data
"""

df_src, src_entities, src_label_max_len = OntologyEntitiesData(
    df_entities_file=SRC_ENTITIES_FILE,
    label_col=LABEL_COL,
    new_ent_col_name="SrcEntity",
    new_label_col_name="SrcLabel"
).get_dfs()

df_tgt, tgt_entities, tgt_label_max_len = OntologyEntitiesData(
    df_entities_file=TGT_ENTITIES_FILE,
    label_col=LABEL_COL,
    new_ent_col_name="TgtEntity",
    new_label_col_name="TgtLabel"
).get_dfs()

df_src.to_csv(r"df_src.csv")
df_tgt.to_csv(r"df_tgt.csv")

"""# ---

## Training

### Cross-Encoders (CE)

#### Sap-BERT (CE)
"""

CE_MODEL_NAME = (
    "cambridgeltl/SapBERT-from-PubMedBERT-fulltext"
)

config = CrossEncoderTrainingConfig(
    model_name=CE_MODEL_NAME,
    dataset_path="df_train_final.csv",
    output_dir="sap_bert_ce",
    batch_size=32,
    epochs=2,
    learning_rate=1e-5,
    max_length=512
)

trainer = BiomedicalCrossEncoderTrainer(config)
trainer.train()

"""#### PubMed-BERT (CE)"""

CE_MODEL_NAME = (
    "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext"
)

config = CrossEncoderTrainingConfig(
    model_name=CE_MODEL_NAME,
    dataset_path="df_train_final.csv",
    output_dir="pubmed_bert_ce",
    batch_size=32,
    epochs=2,
    learning_rate=1e-5,
    max_length=512
)

trainer = BiomedicalCrossEncoderTrainer(config)
trainer.train()

"""### Sentence-Transformers (ST)"""

# Prepare positives only set
df = pd.read_csv(r"df_train_final.csv")

df[df['label'] == 1].to_csv(r"df_train_final_positives.csv")

"""#### SAP-Bert (ST)"""

ST_MODEL_NAME = (
    "cambridgeltl/SapBERT-from-PubMedBERT-fulltext"
)

config = TrainingConfig(
    model_name=ST_MODEL_NAME,
    dataset_path="df_train_final_positives.csv",
    output_dir="sap_bert_st",
    batch_size=128,
    epochs=5,
    learning_rate=1e-5,
    max_seq_length=512
)

trainer = BiomedicalSentenceTransformerTrainer(config)
trainer.train()

"""#### PubMed S-BERT (ST)"""

ST_MODEL_NAME = (
    "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext"
)

config = TrainingConfig(
    model_name=ST_MODEL_NAME,
    dataset_path="df_train_final_positives.csv",
    output_dir="pubmed_bert_st",
    batch_size=128,
    epochs=5,
    learning_rate=1e-5,
    max_seq_length=512
)

trainer = BiomedicalSentenceTransformerTrainer(config)
trainer.train()

"""### (LM) Cross-Encoder"""

train_df = pd.read_csv("df_train_final_local.csv")
val_df = pd.read_csv("df_val_final_local.csv")

CE_MODEL_NAME = (
    "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext"
)

config = CrossEncoderTrainingConfig(
    model_name=CE_MODEL_NAME,
    dataset_path="df_train_final.csv",
    output_dir="pubmed_bert_ce",
    batch_size=32,
    epochs=2,
    learning_rate=1e-5,
    max_length=512
)

trainer = BiomedicalCrossEncoderTrainer(config)
trainer.train(
    train_df=train_df,
    val_df=val_df
)

"""### (LM) Sentence Transformer"""

train_df = pd.read_csv("df_train_final_local.csv")
val_df = pd.read_csv("df_val_final_local.csv")

train_df = train_df[train_df['label'] == 1]
val_df = val_df[val_df['label'] == 1]

ST_MODEL_NAME = (
    # "cambridgeltl/SapBERT-from-PubMedBERT-fulltext"
    "sentence-transformers/all-MiniLM-L6-v2"
)

config = TrainingConfig(
    model_name=ST_MODEL_NAME,
    dataset_path="df_train_final_positives.csv",
    output_dir="sap_bert_st",
    batch_size=128,
    epochs=5,
    learning_rate=1e-5,
    max_seq_length=512
)

trainer = BiomedicalSentenceTransformerTrainer(config)

trainer.train(
    train_df=train_df,
    val_df=val_df
)

"""# ---

## Matching

### FINE-TUNED
"""

def run_mathcing_BI(bi, results_file_name, df_src, df_tgt):
  config = RetrievalConfig(
      model_path=bi,
      batch_size=128,
      top_k=10
  )
  retriever = OntologyTopKRetriever(config)
  results = retriever.run(df_src, df_tgt)
  results.to_csv(results_file_name)


def run_matching_CE(ce, bi_candidates, results_file_name):
  config = CrossEncoderRerankerConfig(
      model_path=ce,
      batch_size=64
  )
  reranker = CrossEncoderOntologyReranker(config)
  candidates_df = pd.read_csv(bi_candidates)
  reranked_df = reranker.rerank(candidates_df)
  reranked_df.to_csv(results_file_name)

BI_MATCHING = [
     {"bi": "sap_bert_st/best_model", "bi_file": "trained_sap_candidates.csv"},

     {"bi": "pubmed_bert_st/best_model", "bi_file": "trained_pub_candidates.csv"}
]

CE_MATCHING = [
     {"ce": "sap_bert_ce/best_model", "ce_file": "trained_sap_sap_matches.csv",
     "candidates_file": "trained_sap_candidates.csv"},  # sap-sap ; ce/bi

     {"ce": "sap_bert_ce/best_model", "ce_file": "trained_sap_pub_matches.csv",
     "candidates_file": "trained_pub_candidates.csv"},  # sap-pub ; ce/bi

     {"ce": "pubmed_bert_ce/best_model", "ce_file": "trained_pub_sap_matches.csv",
     "candidates_file": "trained_sap_candidates.csv"},  # pub-sap ; ce/bi

     {"ce": "pubmed_bert_ce/best_model", "ce_file": "trained_pub_pub_matches.csv",
     "candidates_file": "trained_pub_candidates.csv"},  # pub-pub ; ce/bi
]

for config_bi in BI_MATCHING:
  run_mathcing_BI(
      bi=config_bi['bi'],
      results_file_name=config_bi['bi_file'],
      df_src=df_src,
      df_tgt=df_tgt
  )

for config_ce in CE_MATCHING:
  run_matching_CE(
      ce=config_ce['ce'],
      bi_candidates=config_ce['candidates_file'],
      results_file_name=config_ce['ce_file']
  )

"""### (LM) Sentence Transformer"""

import torch
import pandas as pd
from sentence_transformers import SentenceTransformer
from tqdm.auto import tqdm


def rank_targets_for_sources(
    df,
    model_name,
    top_k=100,
    embedding_batch_size=512,
    search_batch_size=1024,
    device=None,
):

    if device is None:
        device = (
            "cuda"
            if torch.cuda.is_available()
            else "cpu"
        )

    # =====================================================
    # UNIQUE ENTITIES
    # =====================================================

    src_df = (
        df[
            ["SrcEntity", "SrcLabel"]
        ]
        .drop_duplicates("SrcEntity")
        .reset_index(drop=True)
    )

    tgt_df = (
        df[
            ["TgtEntity", "TgtLabel"]
        ]
        .drop_duplicates("TgtEntity")
        .reset_index(drop=True)
    )

    print(
        f"Sources: {len(src_df):,}"
    )

    print(
        f"Targets: {len(tgt_df):,}"
    )

    # =====================================================
    # MODEL
    # =====================================================

    model = SentenceTransformer(
        model_name,
        device=device
    )

    # =====================================================
    # ENCODE SOURCES
    # =====================================================

    src_emb = model.encode(
        src_df["SrcLabel"]
        .astype(str)
        .tolist(),
        batch_size=embedding_batch_size,
        convert_to_tensor=True,
        normalize_embeddings=True,
        show_progress_bar=True,
    )

    # =====================================================
    # ENCODE TARGETS
    # =====================================================

    tgt_emb = model.encode(
        tgt_df["TgtLabel"]
        .astype(str)
        .tolist(),
        batch_size=embedding_batch_size,
        convert_to_tensor=True,
        normalize_embeddings=True,
        show_progress_bar=True,
    )

    tgt_emb = tgt_emb.to(device)

    # =====================================================
    # RETRIEVAL
    # =====================================================

    results = []

    for start in tqdm(
        range(
            0,
            len(src_emb),
            search_batch_size
        ),
        desc="Ranking"
    ):

        end = min(
            start + search_batch_size,
            len(src_emb)
        )

        src_batch = (
            src_emb[start:end]
            .to(device)
        )

        # cosine because embeddings normalized
        similarities = (
            src_batch @ tgt_emb.T
        )

        top_scores, top_indices = (
            torch.topk(
                similarities,
                k=min(
                    top_k,
                    len(tgt_df)
                ),
                dim=1
            )
        )

        top_scores = (
            top_scores
            .cpu()
            .numpy()
        )

        top_indices = (
            top_indices
            .cpu()
            .numpy()
        )

        for local_idx in range(
            len(top_indices)
        ):

            src_idx = (
                start + local_idx
            )

            src_entity = (
                src_df.iloc[src_idx]
                ["SrcEntity"]
            )

            src_label = (
                src_df.iloc[src_idx]
                ["SrcLabel"]
            )

            for rank, (
                tgt_idx,
                score
            ) in enumerate(
                zip(
                    top_indices[local_idx],
                    top_scores[local_idx]
                ),
                start=1
            ):

                results.append(
                    {
                        "SrcEntity":
                            src_entity,

                        "SrcLabel":
                            src_label,

                        "TgtEntity":
                            tgt_df.iloc[tgt_idx]
                            ["TgtEntity"],

                        "TgtLabel":
                            tgt_df.iloc[tgt_idx]
                            ["TgtLabel"],

                        "score":
                            float(score),

                        "rank":
                            rank
                    }
                )

        del similarities

        if device == "cuda":
            torch.cuda.empty_cache()

    return pd.DataFrame(results)

df = pd.read_csv(r"df_holdout_local.csv")

reranked_st = rank_targets_for_sources(
    df=df,
    model_name="sap_bert_st/best_model",
    top_k=100,
    embedding_batch_size=128,
    search_batch_size=1024,
)

reranked_st.to_csv(r"reranked_st.csv")

gt = df[['SrcEntity', 'TgtEntity (True)']].drop_duplicates(ignore_index=True)

evaluate_retrieval(
    reranked_st,
    gt
)

df = pd.read_csv(r"df_holdout_local.csv")

reranked_st_untrained = rank_targets_for_sources(
    df=df,
    model_name="cambridgeltl/SapBERT-from-PubMedBERT-fulltext",
    top_k=100,
    embedding_batch_size=512,
    search_batch_size=1024,
)

reranked_st_untrained.to_csv(r"reranked_st_untrained.csv")

gt = df[['SrcEntity', 'TgtEntity (True)']].drop_duplicates(ignore_index=True)

evaluate_retrieval(
    reranked_st_untrained,
    gt
)

"""### (LM) Cross-Encoder"""

import numpy as np
import pandas as pd
from sentence_transformers import CrossEncoder
from tqdm.auto import tqdm


def cross_encoder_rerank(
    df: pd.DataFrame,
    model_name: str,
    batch_size: int = 64,
    top_k: int = 100,
    device: str = None
):
    """
    Cross-encoder reranking for ontology matching.

    Steps:
    - Group by SrcEntity
    - Score (SrcLabel, TgtLabel) pairs
    - Rerank per source
    """

    if device is None:
        import torch
        device = "cuda" if torch.cuda.is_available() else "cpu"

    # ==========================================================
    # LOAD MODEL
    # ==========================================================

    model = CrossEncoder(
        model_name,
        device=device
    )

    results = []

    # ==========================================================
    # GROUP BY SOURCE
    # ==========================================================

    grouped = df.groupby("SrcEntity")

    for src_entity, group in tqdm(grouped):

        src_label = group["SrcLabel"].iloc[0]

        tgt_labels = group["TgtLabel"].astype(str).tolist()
        tgt_entities = group["TgtEntity"].tolist()

        src_pairs = [
            (src_label, tgt_label)
            for tgt_label in tgt_labels
        ]

        # ======================================================
        # SCORE IN BATCHES
        # ======================================================

        scores = model.predict(
            src_pairs,
            batch_size=batch_size,
            show_progress_bar=False
        )

        scores = np.array(scores)

        scores = scores[:, 1]

        # ======================================================
        # SORT BY SCORE
        # ======================================================

        ranked_idx = np.argsort(-scores)

        for rank, idx in enumerate(ranked_idx[:top_k]):

            results.append({
                "SrcEntity": src_entity,
                "SrcLabel": src_label,
                "TgtEntity": tgt_entities[idx],
                "TgtLabel": tgt_labels[idx],
                "score": float(scores[idx]),
                "rank": rank + 1
            })

    return pd.DataFrame(results)

df = pd.read_csv(r"df_holdout_local.csv")

reranked_ce = cross_encoder_rerank(
    df,
    model_name="pubmed_bert_ce/best_model",
    top_k=100
)

reranked_ce.to_csv(r"reranked_ce.csv")

gt = df[['SrcEntity', 'TgtEntity (True)']].drop_duplicates(ignore_index=True)

evaluate_retrieval(
    reranked_ce,
    gt
)

"""#

---

## Final Alignments & Evaluation
"""

df_holdout = pd.read_csv(r"df_holdout.csv", index_col=0)

df_holdout['SrcEntity'] = df_holdout['SrcEntity'].apply(lambda x: str(x))
df_holdout['TgtEntity'] = df_holdout['TgtEntity'].apply(lambda x: str(x))

"""### FINE-TUNED"""

ALIGNMENTS = [
     {"type": "ST", "model_score_col": "score", "model_matches_file": r"trained_sap_candidates.csv"},  # sap bi

     {"type": "ST", "model_score_col": "score", "model_matches_file": r"trained_pub_candidates.csv"},  # pub bi

     {"type": "CE",
      "model_score_col": "cross_encoder_score",
      "model_matches_file": r"trained_sap_sap_matches.csv"},  # sap-sap ; ce/bi

     {"type": "CE",
      "model_score_col": "cross_encoder_score",
      "model_matches_file": r"trained_sap_pub_matches.csv"},  # sap-pub ; ce/bi

     {"type": "CE",
      "model_score_col": "cross_encoder_score",
      "model_matches_file": r"trained_pub_sap_matches.csv"},  # pub-sap ; ce/bi

     {"type": "CE",
      "model_score_col": "cross_encoder_score",
      "model_matches_file": r"trained_pub_pub_matches.csv"},  # pub-pub ; ce/bi
]

for config_alignment in ALIGNMENTS:
  results = pd.read_csv(config_alignment["model_matches_file"])

  matcher = AdaptiveTopKMatcher(
      AdaptiveTopKConfig(
          score_col=config_alignment["model_score_col"],
          tau_min=0.78,
          delta=0.04,
          ratio_min=0.92
      )
  )
  df_alignments = matcher.filter(results)

  df_alignments['SrcEntity'] = df_alignments['SrcEntity'].apply(lambda x: str(x))
  df_alignments['TgtEntity'] = df_alignments['TgtEntity'].apply(lambda x: str(x))

  PipelineEvaluation(
      df_alignments,
      df_holdout,
      True,
      f"Evaluation ({config_alignment['model_matches_file']})"
  )

  if config_alignment['type'] == "ST":
    st_recall_at_1 = recall_at_1_sentence_transformer(df_alignments, df_holdout)
    print(f"ST Recall@1 : {st_recall_at_1}")
  elif config_alignment['type'] == "CE":
    ce_recall_at_1 = recall_at_1(df_alignments, df_holdout)
    print(f"CE Recall@1 : {ce_recall_at_1}")
    print()

    alpha = 0.8

    results['final_score'] = results['score'] * alpha + results['cross_encoder_score'] * (1 - alpha)

    matcher = AdaptiveTopKMatcher(
        AdaptiveTopKConfig(
            score_col="final_score",
            tau_min=0.78,
            delta=0.04,
            ratio_min=0.92
        )
    )

    df_alignments_combined = matcher.filter(results)

    df_alignments_combined['SrcEntity'] = df_alignments_combined['SrcEntity'].apply(lambda x: str(x))
    df_alignments_combined['TgtEntity'] = df_alignments_combined['TgtEntity'].apply(lambda x: str(x))

    PipelineEvaluation(
        df_alignments_combined,
        df_holdout,
        True,
        f"Evaluation ({config_alignment["model_matches_file"]} COMBINED SCORES)"
    )

  print("=" * 50)
  print("+" * 50)
  print("=" * 50)

"""#

---


"""

# Alignment wrt ST score:
results = pd.read_csv(r"df_st_results.csv")

matcher = AdaptiveTopKMatcher(
    AdaptiveTopKConfig(
        score_col="score",
        tau_min=0.78,
        delta=0.04,
        ratio_min=0.92
    )
)

df_alignments = matcher.filter(results)

df_alignments.to_csv(r"df_alignments_st.csv")

df_alignments['SrcEntity'] = df_alignments['SrcEntity'].apply(lambda x: str(int(x)))
df_alignments['TgtEntity'] = df_alignments['TgtEntity'].apply(lambda x: str(x))

PipelineEvaluation(
    df_alignments,
    df_holdout,
    True,
    "Evaluation (ST)"
)

st_recall_at_1 = recall_at_1_sentence_transformer(
    df_alignments, df_holdout
)

print(f"ST Recall@1 : {st_recall_at_1}")

# ==========
results = pd.read_csv(r"df_ce_results.csv")

matcher = AdaptiveTopKMatcher(
    AdaptiveTopKConfig(
        score_col="cross_encoder_score",
        tau_min=0.78,
        delta=0.04,
        ratio_min=0.92
    )
)

df_alignments = matcher.filter(results)

df_alignments.to_csv(r"df_alignments_ce.csv")

df_alignments['SrcEntity'] = df_alignments['SrcEntity'].apply(lambda x: str(int(x)))
df_alignments['TgtEntity'] = df_alignments['TgtEntity'].apply(lambda x: str(x))

PipelineEvaluation(
    df_alignments,
    df_holdout,
    True,
    "Evaluation (CE)"
)

ce_recall_at_1 = recall_at_1(
    df_alignments, df_holdout
)

print(f"CE Recall@1 : {ce_recall_at_1}")

# ==========
results = pd.read_csv(r"df_ce_results.csv")

alpha = 0.8

results['final_score'] = results['score'] * alpha + results['cross_encoder_score'] * (1 - alpha)

matcher = AdaptiveTopKMatcher(
    AdaptiveTopKConfig(
        score_col="final_score",
        tau_min=0.78,
        delta=0.04,
        ratio_min=0.92
    )
)

df_alignments = matcher.filter(results)

df_alignments.to_csv(r"df_alignments_combined.csv")

df_alignments['SrcEntity'] = df_alignments['SrcEntity'].apply(lambda x: str(int(x)))
df_alignments['TgtEntity'] = df_alignments['TgtEntity'].apply(lambda x: str(x))

PipelineEvaluation(
    df_alignments,
    df_holdout,
    True,
    "Evaluation (ST + CE scores)"
)

print("Done.")

"""#

---

# ---

---



---

# Other Code
"""

